name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          PROJECTS_NOTION_DATABASE_ID: ${{ secrets.PROJECTS_NOTION_DATABASE_ID }}
          BLOG_NOTION_DATABASE_ID: ${{ secrets.BLOG_NOTION_DATABASE_ID }}
          STAYS_NOTION_DATABASE_ID: ${{ secrets.STAYS_NOTION_DATABASE_ID }}
        run: npm run build
        
      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npm run deploy
